### PR TITLE
Adding Beeceptor.com - An HTTP inspecting/mocking/proxying service

### PR DESCRIPTION
**Pull request by ankitjaininfo**
Hi,

I would like to add Beeceptor. It gives named endpoints to build mock API responses and inspecting HTTP payloads.

### CODE REVIEW

**Comment by fzaninotto** [comment]
As it's a paid service, please add it to the SaaS tools section instead.

**Comment by ankitjaininfo** [comment]
Thank you Francois for suggestion. I just moved it to SaaS Tools section.

**Comment by ankitjaininfo** [comment]
@fzaninotto - Just want to check if there is more feedback, I can incorporate. In any case, I have moved Beeceptor to SaaS section.

**Review by fzaninotto — APPROVED** [review]

**Comment by fzaninotto** [comment]
Thanks!

**Pull request merged**
