### PR TITLE
Proposing the inclusion of a new and trending article about RESTful

### PR DESCRIPTION
**Pull request by RichardSilveira**
This article was published by the huge ITNEXT medium editors!

* I'm covering main concepts such as:
- HATEOAS - Hypermedia As The Engine Of Application State,
- Resources and representations,
- Addressability,
- Idempotency in REST,
- Richardson's REST Maturity Model.
- Media types
- API Versioning

* I've created a GitHub project as well that you can run easily with docker, which covers the content that I've presented in this article.
- https://github.com/RichardSilveira/RESTful

* My article was reposted by Vintage Global - a huge architecture community on Linkedin.
https://www.linkedin.com/feed/update/urn%3Ali%3Aactivity%3A6726141404436799488/

[Why it's a trending article](http://bit.ly/whythisarticle)

### CODE REVIEW

**Comment by RichardSilveira** [comment]
Plus, I've presented it on my MBA in the Software Architecture field. Note that I have added good book references at the end of this article.

**Comment by fzaninotto** [comment]
Sorry, we don't link to paid content.

**Comment by waldyrious** [comment]
Hey @fzaninotto, I just came across this and was a little puzzled — I was able to read [the article](https://itnext.io/how-to-build-a-restful-api-a-deep-dive-into-rest-apis-215188f80854) freely and it did contain useful (IMHO) information about what a REST API is and general principles about how to implement one. I didn't see any paywalled content. Am I missing something? Did the post somehow change between the time this PR was submitted and now?

**Comment by fzaninotto** [comment]
I believe the post changed since the PR was opened - Authors can choose to put their articles behind a paywall or not on Medium.

**Comment by waldyrious** [comment]
I see, thanks for the context. Since the article is now public, would you be open to accepting this PR now? Even though there's a risk it would be made inaccessible again, I'd consider an eventual switch back to paid content to be similar to a link going dead, which has happened in the past (see PRs #132 to #135) and in which case the solution is to remove the link when that happens.

**Pull request closed without merging**
