### PR TITLE
CI: Add a github action that could help to check if links are dead

### PR DESCRIPTION
**Pull request by olivierodo**
Hi 👋,
After checking some project on the list i realized that a few of the links are dead.
Then i'm proposing to add a github action that would allow to check if some link are dead.

As of now the github action is triggered by push event but we could update it to have it triggered periodically.

Next step: Enable github action on the repo if it hasn't been activated yet.

### CODE REVIEW

**Comment by olivierodo** [comment]
While running it on my fork:
image

Full detail: https://github.com/olivierodo/awesome-rest/actions/runs/3766965379/jobs/6404026277

**Comment by fzaninotto** [comment]
Awesome!

I have two questions:

- why isn't this PR marked as failed, given it contains a failed job?
- Could you update/remove the current dead links, as following PRs would fail if you don't?

**Comment by olivierodo** [comment]
@fzaninotto thank you for the feedbacks. 🙏

About your questions:
1. Since my pull request is from a fork, i'm not allowed to triggered the github action on this repo. If you want you can tweak this config in [your action settings](https://github.com/marmelab/awesome-rest/settings/actions)
2. I updated the list, however about i did major changes on:
    * Update / remove dead links
    * Trying to move the links to https
    * A few links do not have valid https cert, better let them use http, FYI the links are:
      *  https://blog.ulf-wendel.de/2014/mysql-5-7-http-plugin-mysql/
      *  https://lakion.com/lionframe
      * https://tastypieapi.org/
 4. For some reason the swagger.io links response a weird error `Z_DATA_ERROR` i had to add it to the ignore list for the moment, I'll investigate and create a fix on the github action if required.

Let me know anything else i can help 🎉

**Review by fzaninotto — APPROVED** [review]

**Comment by fzaninotto** [comment]
Awesome, thanks a lot!

**Pull request merged**
