### PR TITLE
Added hurl, httpbin, requestbin & deckofcards API

### PR DESCRIPTION
**Pull request by mansilladev**

### CODE REVIEW

**Comment by mansilladev** [comment]
Hurl is a very popular web-based HTTP request tool. Easy to add headers, params, make PUT/POST/DELETE calls, etc. 

httpbin is like a Swiss Army Knife for HTTP -- mock responses; forcing delays; cookie handling; streaming data; returning any arbitrary status code

RequestBin is a webhook/callback testing service. Extremely useful.

Deck Of Cards API -- nice open API (and open source project) for creating a deck of cards, shuffling, drawing cards, etc.

**Comment by fzaninotto** [comment]
I'd put httpbin and requestbin under the "mocking" section.

**Comment by mansilladev** [comment]
@fzaninotto Updated.

**Comment by fzaninotto** [comment]
Thanks!

**Pull request merged**
